// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqHRC-2PTm9e2daLOFy_V6GL3KdxZLlOc',
    appId: '1:322166710554:web:0de0908930491630660ca3',
    messagingSenderId: '322166710554',
    projectId: 'hedieaty-8137a',
    authDomain: 'hedieaty-8137a.firebaseapp.com',
    storageBucket: 'hedieaty-8137a.firebasestorage.app',
    measurementId: 'G-EW0T4PMDYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc6V0xxJsVSBjqqK5XpfiqIRXnRLknGWA',
    appId: '1:322166710554:android:7f4b824ad8416f2a660ca3',
    messagingSenderId: '322166710554',
    projectId: 'hedieaty-8137a',
    storageBucket: 'hedieaty-8137a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zEZTc0w4Wl8rfnCn-IFYSyB3UgMXhc8',
    appId: '1:322166710554:ios:7d349b55e6212c13660ca3',
    messagingSenderId: '322166710554',
    projectId: 'hedieaty-8137a',
    storageBucket: 'hedieaty-8137a.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqHRC-2PTm9e2daLOFy_V6GL3KdxZLlOc',
    appId: '1:322166710554:web:5bf0081ceb03bd82660ca3',
    messagingSenderId: '322166710554',
    projectId: 'hedieaty-8137a',
    authDomain: 'hedieaty-8137a.firebaseapp.com',
    storageBucket: 'hedieaty-8137a.firebasestorage.app',
    measurementId: 'G-NG0ZNT63CF',
  );

}